# Generated by Django 5.2.14 on 2026-05-29 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0002_produto_estoque_atual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimentacao",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SAIDA", "Saída"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=10,
                        verbose_name="tipo de movimentação",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("origem", models.CharField(blank=True, max_length=100)),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_estoque",
                        to="produtos.produto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_estoque",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "movimentação de estoque",
                "verbose_name_plural": "movimentações de estoque",
                "ordering": ["-data"],
            },
        ),
    ]

