# Generated by Django 5.2.14 on 2026-05-29 14:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "codigo_interno",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="código interno"
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="código de barras",
                    ),
                ),
                ("categoria", models.CharField(blank=True, max_length=100)),
                (
                    "unidade_medida",
                    models.CharField(max_length=20, verbose_name="unidade de medida"),
                ),
                (
                    "preco_custo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="preço de custo",
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="preço de venda",
                    ),
                ),
                (
                    "estoque_minimo",
                    models.PositiveIntegerField(
                        default=0, verbose_name="estoque mínimo"
                    ),
                ),
                (
                    "ncm",
                    models.CharField(blank=True, max_length=20, verbose_name="NCM"),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="fornecedores.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["nome"],
            },
        ),
    ]

