# Generated by Django 5.2.14 on 2026-05-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="estoque_atual",
            field=models.PositiveIntegerField(default=0, verbose_name="estoque atual"),
        ),
    ]
