# Generated by Django 5.2.15 on 2026-06-10 17:10

import re
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def inicializar_sequencia(apps, schema_editor):
    Produto = apps.get_model("produtos", "Produto")
    Sequencia = apps.get_model("produtos", "SequenciaCodigoProduto")
    padrao = re.compile(r"^PROD(?P<numero>\d+)$")
    maior_numero = 0
    codigos = Produto.objects.filter(codigo_interno__startswith="PROD").values_list(
        "codigo_interno", flat=True
    )
    for codigo in codigos:
        correspondencia = padrao.fullmatch(codigo or "")
        if correspondencia:
            maior_numero = max(maior_numero, int(correspondencia.group("numero")))
    Sequencia.objects.update_or_create(chave=1, defaults={"ultimo_numero": maior_numero})


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_produto_estoque_atual"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenciaCodigoProduto",
            fields=[
                (
                    "chave",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ultimo_numero", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "sequência de código de produto",
                "verbose_name_plural": "sequências de códigos de produtos",
            },
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo_interno",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="código interno"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="preço de custo",
            ),
        ),
        migrations.RunPython(inicializar_sequencia, migrations.RunPython.noop),
    ]

