# Generated by Django 5.2.14 on 2026-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=150, verbose_name="razão social"),
                ),
                ("nome_fantasia", models.CharField(blank=True, max_length=150)),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição estadual"
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço"
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=2)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "fornecedor",
                "verbose_name_plural": "fornecedores",
                "ordering": ["razao_social"],
            },
        ),
    ]
