# Generated by Django 5.2.15 on 2026-06-10 19:57

import administracao.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracao", "0003_configuracaosistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Recomendado: PNG transparente 512x512",
                upload_to="empresa/logos/",
                validators=[
                    administracao.validators.ValidadorLogotipo(
                        extensoes_permitidas=("png", "jpg", "jpeg", "svg"),
                        tamanho_maximo_mb=2,
                    )
                ],
                verbose_name="logo do sistema",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="logo_impressao",
            field=models.FileField(
                blank=True,
                help_text="Recomendado: PNG ou SVG horizontal 1200x400",
                upload_to="empresa/logos/impressao/",
                validators=[
                    administracao.validators.ValidadorLogotipo(
                        extensoes_permitidas=("png", "svg"), tamanho_maximo_mb=5
                    )
                ],
                verbose_name="logo para impressão",
            ),
        ),
    ]
