# Generated by Django 5.2.15 on 2026-06-17 00:51

import administracao.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_backupregistro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'verbose_name': 'configuração do sistema', 'verbose_name_plural': 'configuração do sistema'},
        ),
        migrations.AlterField(
            model_name='backupregistro',
            name='tipo',
            field=models.CharField(choices=[('BACKUP', 'Backup'), ('RESTAURACAO', 'Restauração')], max_length=12),
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='tipo',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('VEICULOS', 'Veículos')], default='GERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='dias_antecedencia_aniversario',
            field=models.PositiveIntegerField(default=0, help_text='0 = avisar somente no dia; 7 = avisar com uma semana de antecedência.', verbose_name='dias de antecedência para aviso'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='mensagem_rodape_documentos',
            field=models.CharField(default='Documento gerado pelo sistema GESTIX.', max_length=255, verbose_name='mensagem de rodapé dos documentos'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='mostrar_logo_impressoes',
            field=models.BooleanField(default=True, verbose_name='mostrar logo nas impressões'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='notificacoes_aniversario_ativas',
            field=models.BooleanField(default=True, verbose_name='ativar notificações de aniversário'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='tempo_logout_inatividade',
            field=models.PositiveIntegerField(default=15, help_text='Tempo em minutos antes de encerrar automaticamente uma sessão inativa.', verbose_name='tempo para logout por inatividade (minutos)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cor_primaria',
            field=models.CharField(default='#0D6EFD', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor primária'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cor_secundaria',
            field=models.CharField(default='#6C757D', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor secundária'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, verbose_name='inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=30, verbose_name='inscrição municipal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo_impressao',
            field=models.FileField(blank=True, help_text='Recomendado: PNG ou SVG horizontal 1200x400', upload_to='empresa/logos/impressao/', validators=[administracao.validators.ValidadorLogotipo(extensoes_permitidas=('png', 'svg'), tamanho_maximo_mb=5)], verbose_name='logo para impressão'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=180, verbose_name='razão social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsavel',
            field=models.CharField(blank=True, max_length=150, verbose_name='responsável'),
        ),
    ]

