# Generated by Django 5.2.15 on 2026-06-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_alter_configuracaosistema_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproduto',
            name='tipo',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('VEICULOS', 'Veículos')], default='GERAL', max_length=10),
        ),
    ]
