# Generated by Django 5.2.15 on 2026-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0008_alter_categoriaproduto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='mensagem_rodape_documentos',
            field=models.CharField(default='Documento gerado pelo sistema AXIORA ERP.', max_length=255, verbose_name='mensagem de rodapé dos documentos'),
        ),
    ]
