# Generated by Django 5.2.15 on 2026-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'perfil de usuário', 'verbose_name_plural': 'perfis de usuários'},
        ),
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão'), ('CANCELAMENTO', 'Cancelamento'), ('FINALIZACAO', 'Finalização'), ('IMPRESSAO', 'Impressão'), ('BACKUP', 'Backup'), ('RESTAURACAO', 'Restauração'), ('PAGAMENTO', 'Pagamento'), ('RECEBIMENTO', 'Recebimento'), ('MOVIMENTACAO_ESTOQUE', 'Movimentação de estoque'), ('ABERTURA_CAIXA', 'Abertura de caixa'), ('FECHAMENTO_CAIXA', 'Fechamento de caixa'), ('ERRO', 'Erro')], max_length=30),
        ),
    ]

