# Generated by Django 5.2.15 on 2026-06-10 01:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordens_servico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="assinatura_responsavel_execucao",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="assinaturas_os/",
                verbose_name="Assinatura do Responsável pela Execução",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="responsavel_execucao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordens_servico_executadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável pela Execução",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="valor_deslocamento",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor do Deslocamento",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordemservico",
            constraint=models.CheckConstraint(
                condition=models.Q(valor_deslocamento__gte=0),
                name="os_valor_deslocamento_nao_negativo",
            ),
        ),
    ]
