# Generated by Django 5.2.15 on 2026-06-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordens_servico", "0002_deslocamento_responsavel_execucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="data_finalizacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Finalização"
            ),
        ),
    ]

