# Generated by Django 5.2.14 on 2026-06-03 01:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_venda_forma_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="data_primeiro_vencimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="data do primeiro vencimento"
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="intervalo_parcelas",
            field=models.PositiveIntegerField(
                default=30,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="intervalo entre parcelas",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="observacoes_crediario",
            field=models.TextField(blank=True, verbose_name="observações do crediário"),
        ),
        migrations.AddField(
            model_name="venda",
            name="quantidade_parcelas",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="quantidade de parcelas",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="valor_entrada",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="valor de entrada/sinal",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "PIX"),
                    ("CARTAO_CREDITO", "Cartão de crédito"),
                    ("CARTAO_DEBITO", "Cartão de débito"),
                    ("BOLETO", "Boleto"),
                    ("CREDIARIO", "Crediário"),
                    ("OUTROS", "Outros"),
                ],
                default="DINHEIRO",
                max_length=20,
                verbose_name="forma de pagamento",
            ),
        ),
    ]
