# Generated by Django 5.2.15 on 2026-06-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0003_venda_data_primeiro_vencimento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="cancelada_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="cancelada em"
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="motivo_cancelamento",
            field=models.TextField(blank=True, verbose_name="motivo do cancelamento"),
        ),
        migrations.AddField(
            model_name="venda",
            name="usuario_cancelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas_canceladas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
