# Generated by Django 5.2.15 on 2026-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_cancelamento_rascunho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_DEBITO', 'Cartão de débito'), ('BOLETO', 'Boleto'), ('CREDIARIO', 'Crediário'), ('OUTROS', 'Outros')], default='DINHEIRO', max_length=20, verbose_name='forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacoes_crediario',
            field=models.TextField(blank=True, verbose_name='observações do crediário'),
        ),
    ]

