# Generated by Django 5.2.15 on 2026-06-18 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_tipo_pessoa'),
        ('produtos', '0004_categoria_produto_chassi'),
        ('vendas', '0005_alter_venda_forma_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['produto', 'venda'], name='item_produto_venda_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status', 'data'], name='vendas_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['usuario', 'status', 'data'], name='vendas_user_status_data_idx'),
        ),
    ]
