# Generated by Django 5.2.14 on 2026-06-03 01:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0002_cliente_inscricao_estadual_data_nascimento"),
        ("vendas", "0003_venda_data_primeiro_vencimento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaReceber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_parcela", models.PositiveIntegerField()),
                ("total_parcelas", models.PositiveIntegerField()),
                (
                    "data_emissao",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("PAGA", "Paga"),
                            ("ATRASADA", "Atrasada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=10,
                    ),
                ),
                (
                    "forma_recebimento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("PIX", "PIX"),
                            ("CARTAO_CREDITO", "Cartão de crédito"),
                            ("CARTAO_DEBITO", "Cartão de débito"),
                            ("BOLETO", "Boleto"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_receber",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_receber",
                        to="vendas.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "conta a receber",
                "verbose_name_plural": "contas a receber",
                "ordering": ["data_vencimento", "numero_parcela"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("venda", "numero_parcela"),
                        name="unique_parcela_por_venda",
                    )
                ],
            },
        ),
    ]
