# Generated by Django 5.2.15 on 2026-06-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_tipo_pessoa'),
        ('contas_receber', '0002_contareceber_ordem_servico'),
        ('ordens_servico', '0005_alter_servico_valor_padrao'),
        ('vendas', '0005_alter_venda_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['status', 'data_vencimento'], name='receber_status_venc_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente', 'status', 'data_vencimento'], name='receber_cli_status_idx'),
        ),
    ]
