# Generated by Django 5.2.14 on 2026-05-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fornecedores", "0001_initial"),
        ("produtos", "0002_produto_estoque_atual"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaFiscalEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave_acesso",
                    models.CharField(
                        max_length=44, unique=True, verbose_name="chave de acesso"
                    ),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="número")),
                ("serie", models.CharField(max_length=10, verbose_name="série")),
                ("data_emissao", models.DateTimeField(verbose_name="data de emissão")),
                (
                    "emitente_cnpj",
                    models.CharField(max_length=18, verbose_name="CNPJ do emitente"),
                ),
                (
                    "emitente_razao_social",
                    models.CharField(
                        max_length=150, verbose_name="razão social do emitente"
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADA", "Confirmada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_fiscais_entrada",
                        to="fornecedores.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota fiscal de entrada",
                "verbose_name_plural": "notas fiscais de entrada",
                "ordering": ["-data_emissao"],
            },
        ),
        migrations.CreateModel(
            name="ItemNotaFiscalEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_item", models.PositiveIntegerField()),
                (
                    "codigo_produto",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="código do produto no XML",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="descrição"),
                ),
                (
                    "ncm",
                    models.CharField(blank=True, max_length=20, verbose_name="NCM"),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="unidade de medida"
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_nfe_entrada",
                        to="produtos.produto",
                    ),
                ),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="fiscal.notafiscalentrada",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de nota fiscal de entrada",
                "verbose_name_plural": "itens de nota fiscal de entrada",
                "ordering": ["numero_item"],
                "unique_together": {("nota", "numero_item")},
            },
        ),
    ]

