# Generated by Django 5.2.15 on 2026-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaocaixa',
            options={'ordering': ['-data'], 'verbose_name': 'movimentação de caixa', 'verbose_name_plural': 'movimentações de caixa'},
        ),
        migrations.AlterField(
            model_name='caixa',
            name='observacao_abertura',
            field=models.TextField(blank=True, verbose_name='observação de abertura'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='observacao_fechamento',
            field=models.TextField(blank=True, verbose_name='observação de fechamento'),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_DEBITO', 'Cartão de débito'), ('BOLETO', 'Boleto'), ('OUTROS', 'Outros')], default='DINHEIRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('SANGRIA', 'Sangria'), ('SUPRIMENTO', 'Suprimento'), ('VENDA', 'Venda'), ('CANCELAMENTO', 'Cancelamento')], max_length=12),
        ),
    ]

