# Generated by Django 5.2.15 on 2026-06-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_alter_movimentacaocaixa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('SANGRIA', 'Sangria'), ('SUPRIMENTO', 'Suprimento'), ('VENDA', 'Venda'), ('CANCELAMENTO', 'Cancelamento')], max_length=12),
        ),
    ]
