# Generated by Django 5.2.15 on 2026-06-18 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_alter_movimentacaocaixa_tipo'),
        ('vendas', '0005_alter_venda_forma_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimentacaocaixa',
            index=models.Index(fields=['tipo', 'data'], name='mov_caixa_tipo_data_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocaixa',
            index=models.Index(fields=['forma_pagamento', 'data'], name='mov_caixa_forma_data_idx'),
        ),
    ]
