# Generated by Django 5.2.15 on 2026-06-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_cliente_tipo_pessoa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_envio', models.CharField(choices=[('WHATSAPP_WEB', 'WhatsApp Web'), ('API', 'API')], default='WHATSAPP_WEB', max_length=20)),
                ('provedor_api', models.CharField(choices=[('ZERNIO', 'Zernio'), ('META', 'Meta'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('api_url', models.URLField(blank=True, verbose_name='URL da API')),
                ('api_token', models.CharField(blank=True, max_length=500, verbose_name='token da API')),
                ('numero_remetente', models.CharField(blank=True, max_length=20, verbose_name='número remetente')),
                ('ativo', models.BooleanField(default=True)),
                ('enviar_automaticamente', models.BooleanField(default=False, verbose_name='enviar automaticamente')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração do WhatsApp',
                'verbose_name_plural': 'configurações do WhatsApp',
                'ordering': ['-ativo', '-atualizado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo',), name='whatsapp_apenas_uma_configuracao_ativa')],
            },
        ),
        migrations.CreateModel(
            name='ModeloMensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('COBRANCA', 'Cobrança'), ('ANIVERSARIO', 'Aniversário'), ('ORCAMENTO', 'Orçamento'), ('ORDEM_SERVICO', 'Ordem de Serviço'), ('VENDA', 'Venda'), ('AVULSA', 'Avulsa')], max_length=20)),
                ('mensagem', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modelo de mensagem WhatsApp',
                'verbose_name_plural': 'modelos de mensagem WhatsApp',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['tipo', 'ativo'], name='whatsapp_mo_tipo_5ca8a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilaMensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('COBRANCA', 'Cobrança'), ('ANIVERSARIO', 'Aniversário'), ('ORCAMENTO', 'Orçamento'), ('ORDEM_SERVICO', 'Ordem de Serviço'), ('VENDA', 'Venda'), ('AVULSA', 'Avulsa')], max_length=20)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADA', 'Enviada'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('erro', models.TextField(blank=True)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuário de criação')),
            ],
            options={
                'verbose_name': 'fila de mensagem WhatsApp',
                'verbose_name_plural': 'fila de mensagens WhatsApp',
                'ordering': ['agendada_para', '-criado_em'],
                'indexes': [models.Index(fields=['status', 'agendada_para'], name='whatsapp_fi_status_40dda1_idx'), models.Index(fields=['tipo', 'criado_em'], name='whatsapp_fi_tipo_457007_idx')],
            },
        ),
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('COBRANCA', 'Cobrança'), ('ANIVERSARIO', 'Aniversário'), ('ORCAMENTO', 'Orçamento'), ('ORDEM_SERVICO', 'Ordem de Serviço'), ('VENDA', 'Venda'), ('AVULSA', 'Avulsa')], max_length=20)),
                ('mensagem', models.TextField()),
                ('modo_envio', models.CharField(choices=[('WHATSAPP_WEB', 'WhatsApp Web'), ('API', 'API')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('resposta_api', models.TextField(blank=True, verbose_name='resposta da API')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='data de envio')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensagem WhatsApp',
                'verbose_name_plural': 'mensagens WhatsApp',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='whatsapp_me_status_5342bf_idx'), models.Index(fields=['tipo', 'criado_em'], name='whatsapp_me_tipo_aee10e_idx')],
            },
        ),
    ]
