# Generated by Django 5.2.14 on 2026-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("fisica", "Física"), ("juridica", "Jurídica")],
                        max_length=10,
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="CPF/CNPJ"
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço"
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=2)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nome"],
            },
        ),
    ]
