# Generated by Django 5.2.15 on 2026-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_inscricao_estadual_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('fisica', 'Física'), ('juridica', 'Jurídica')], max_length=10),
        ),
    ]

