# Generated by Django 5.2.15 on 2026-06-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('fisica', 'Física'), ('juridica', 'Jurídica')], max_length=10),
        ),
    ]
